baseURL = "https://septictank.bangunan.co/"
languageCode = "id"
title = "Bio Septictank SNI | Jual dan Jasa Pasang Bio Septictank Bersertifikat SNI"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Distributor Bio Septictank SNI - Jual Bio Septictank berbagai ukuran dengan sertifikasi SNI, harga bersaing, dan layanan pemasangan profesional."
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jual bio septictank", "septictank SNI", "septictank bio", "pemasangan bio septictank", "bio septictank harga terjangkau", "bio septictank berbagai ukuran"]
  base_price = 3000000
  price_range = 500000
  free_shipping = true
  materials = [
  "Bio Septictank ukuran 1-2 orang",
  "Bio Septictank ukuran 3-5 orang",
  "Bio Septictank ukuran 6-10 orang",
  "Bio Septictank custom kapasitas besar",
  "Bio Septictank bersertifikat SNI"
]
  categories = ["Bio Septictank", "Sanitasi", "Peralatan Bangunan"]
  payment_methods = ["COD (Cash On Delivery)", "Transfer Bank", "Bayar Ditempat", "Transfer Setelah Terkirim"]
  area_served = ["Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Cikarang", "Karawang", "Subang", "Cikampek", "Purwakarta", "Rangkas Bitung", "Serang"]
  return_policies = [
  "Barang bisa ditukar dalam 1 hari jika tidak sesuai.",
  "Barang dapat ditolak jika bio septictank tidak sesuai spesifikasi.",
  "Pengembalian gratis untuk produk yang tidak sesuai pesanan."
]

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Distributor Bio Septictank Bersertifikat SNI"
  hero_description = "Kami menawarkan Bio Septictank berkualitas dengan sertifikasi SNI, berbagai ukuran yang cocok untuk kebutuhan rumah tangga hingga industri. Solusi ramah lingkungan untuk pengolahan limbah dengan sistem yang efisien dan tahan lama."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog Bio Septictank"

  # Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan Bio Septictank bersertifikat SNI dengan harga bersaing, kualitas unggul, dan layanan pemasangan profesional di seluruh Indonesia. Gratis konsultasi untuk membantu Anda memilih Bio Septictank yang sesuai dengan kebutuhan."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "septictank.bangunan.co menawarkan berbagai pilihan Bio Septictank dengan sertifikasi SNI untuk pengolahan limbah yang efisien dan ramah lingkungan. Produk kami tahan lama, mudah dipasang, dan harga bersaing. Pilih kami untuk solusi pengolahan limbah yang optimal."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Joko|Andi|Eko|Rudi|Fajar|Hendra|Samsul|Agus|Dedi}"
  message = "{Saya membeli Bio Septictank dari septictank.bangunan.co dan hasilnya {sangat memuaskan|luar biasa|memenuhi harapan}. Instalasi {cepat|lancar|profesional} dan produk {berkualitas tinggi|sangat berkualitas|kokoh}.|Produk Bio Septictank dari septictank.bangunan.co {sangat berkualitas|memuaskan|terbaik} untuk proyek {rumah|bangunan|perumahan} saya. Pengiriman {tepat waktu|cepat|aman} dan layanan {baik|ramah|profesional}.}"
  response = "{Terima kasih atas {kepercayaan|ulasan|testimoni} Anda! Kami senang dapat menyediakan Bio Septictank {berkualitas|terbaik} untuk proyek Anda.|Kami sangat menghargai ulasan Anda. Senang mendengar Anda puas dengan layanan kami.|Kami berkomitmen untuk menyediakan Bio Septictank {berkualitas|terbaik} dengan layanan {optimal|profesional}. Terima kasih atas kepercayaannya!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Rina|Dewi|Wati|Lia|Nina|Ratna|Indah|Sari|Ayu}"
  message = "{septictank.bangunan.co sangat membantu dalam {memilih|menemukan|mencari} Bio Septictank yang {sesuai|tepat} untuk {rumah|proyek} saya. Produk yang saya beli {berkualitas|terbaik|luar biasa} dan {sesuai|tepat} dengan kebutuhan saya.|Produk Bio Septictank dari septictank.bangunan.co {sangat sesuai|benar-benar cocok|luar biasa} dengan {kebutuhan|proyek} saya, dan pelayanan mereka {ramah|profesional|baik}.}"
  response = "{Kami sangat menghargai ulasan Anda. Senang mendengar Anda puas dengan Bio Septictank kami.|Terima kasih atas {kepercayaannya|ulasan positifnya}. Kami senang dapat memenuhi harapan Anda dengan produk kami.|Terima kasih, atas kepercayaannya! Kami akan terus menyediakan produk terbaik untuk kebutuhan Anda.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Budi|Andi|Eko|Rudi|Fajar|Hendra|Samsul|Agus|Dedi}"
  message = "{Produk Bio Septictank dari septictank.bangunan.co {sangat cocok|tepat|luar biasa} untuk proyek {perumahan|bangunan|renovasi} saya. Proses pembelian {lancar|mudah|cepat} dan pengiriman {tepat waktu|aman|tanpa masalah}.|Saya membeli Bio Septictank dari septictank.bangunan.co untuk proyek saya, dan produk ini {sangat berkualitas|luar biasa|memenuhi harapan} serta pengirimannya {cepat|aman|profesional}.}"
  response = "{Terima kasih! Kami berkomitmen untuk menyediakan Bio Septictank {berkualitas|terbaik} dengan layanan {terbaik|optimal}.|Kami menghargai ulasan positif Anda. Terima kasih telah memilih kami!|Senang mendengar Anda puas dengan produk kami. Terima kasih atas kepercayaannya!}"
  rating = 4.5

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Budi|Joko|Eko|Rudi|Fajar|Hendra|Samsul|Agus|Dedi}"
  message = "{Saya sangat puas dengan Bio Septictank dari septictank.bangunan.co. Kualitasnya {sangat baik|luar biasa|terbaik} dan tahan lama untuk proyek saya.|Bio Septictank dari septictank.bangunan.co {benar-benar berkualitas|sangat baik|kokoh} dan sesuai dengan kebutuhan proyek saya. Proses pembelian {mudah|cepat|lancar} dan layanan mereka {profesional|ramah|memuaskan}.}"
  response = "{Senang mendengar Anda puas dengan Bio Septictank kami. Terima kasih atas kepercayaannya!|Terima kasih atas ulasan Anda. Kami senang dapat memenuhi kebutuhan proyek Anda.|Kami berkomitmen untuk menyediakan produk berkualitas tinggi, dan kami senang mendengar Anda puas.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Dewi|Wati|Lia|Nina|Ratna|Indah|Sari|Ayu}"
  message = "{Pelayanan septictank.bangunan.co {sangat memuaskan|luar biasa|baik}. Produk Bio Septictank yang saya beli {sangat berkualitas|berkualitas tinggi|memenuhi harapan} dan {sesuai|tepat|cocok} dengan {harapan|keinginan|kebutuhan} saya.|Produk Bio Septictank dari septictank.bangunan.co {berkualitas tinggi|terbaik|memuaskan} dan layanan mereka {ramah|profesional|baik}.}"
  response = "{Terima kasih! Kami senang dapat membantu Anda dengan Bio Septictank berkualitas.|Kami menghargai kepercayaan Anda. Terima kasih atas ulasan positifnya!|Senang mendengar Anda puas dengan produk kami. Terima kasih atas kepercayaannya!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Budi|Joko|Andi|Rudi|Fajar|Hendra|Samsul|Agus|Dedi}"
  message = "{Bio Septictank dari septictank.bangunan.co sangat {cocok|sesuai} dengan kebutuhan proyek renovasi rumah saya. Proses pengiriman {cepat|aman|lancar} dan produk {sangat berkualitas|kokoh|berkualitas tinggi}.|Saya membeli Bio Septictank dari septictank.bangunan.co, dan hasilnya {sangat baik|memuaskan|terbaik}. Pengirimannya {tepat waktu|cepat|aman} dan layanan mereka {ramah|profesional|baik}.}"
  response = "{Kami senang mendengar bahwa Anda puas dengan produk kami. Terima kasih atas ulasannya!|Terima kasih atas kepercayaannya. Kami sangat senang mendengar Anda puas dengan Bio Septictank kami.|Kami sangat menghargai ulasan Anda. Terima kasih atas kepercayaannya!}"
  rating = 5

[[params.tabelItems]]
  name = "Bio Septictank 1-2 Orang"
  price = "750.000 /unit"
[[params.tabelItems]]
  name = "Bio Septictank 3-5 Orang"
  price = "2.500.000 /unit"
[[params.tabelItems]]
  name = "Bio Septictank 6-10 Orang"
  price = "2.800.000 /unit"
[[params.tabelItems]]
  name = "Bio Septictank Custom"
  price = "1.750.000 /unit"
[[params.tabelItems]]
  name = "Bio Septictank SNI"
  price = "2.300.000 /unit"

[params.appliList]
  "Bio Septictank 1-2 Orang" = "rumah kecil, kontrakan"
  "Bio Septictank 3-5 Orang" = "rumah sedang, kantor kecil"
  "Bio Septictank 6-10 Orang" = "rumah besar, gedung"
  "Bio Septictank Custom" = "proyek besar, bangunan komersial"
  "Bio Septictank SNI" = "rumah, perkantoran, sekolah"

[params.kegunaanList]
  "Bio Septictank 1-2 Orang" = "solusi sanitasi untuk rumah kecil"
  "Bio Septictank 3-5 Orang" = "menangani limbah rumah tangga dengan kapasitas sedang"
  "Bio Septictank 6-10 Orang" = "menampung limbah rumah besar atau gedung"
  "Bio Septictank Custom" = "desain khusus untuk kebutuhan sanitasi skala besar"
  "Bio Septictank SNI" = "memenuhi standar sanitasi dengan sertifikasi SNI"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
   title = "Distributor Bio Septictank Murah Bersertifikat SNI | "
   highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"